# Chapter 13. Linear Regression

## 13.0 Introduction
## 13.1 Fitting a Line

In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston

boston = load_boston()
features = boston.data[:, 0:2]
target = boston.target

# linear regression
regression = LinearRegression()

# Fit the linear regression
model = regression.fit(features, target)

In [2]:
# View the intercept
model.intercept_

22.485628113468223

In [3]:
# view the feature coefficients
model.coef_

array([-0.35207832,  0.11610909])

* 저것이 베타1, 베타2가 된다.

In [4]:
# 1000을 곱하여 첫번째 집의 가격을 확인한다.
target[0]*1000

24000.0

In [5]:
# predict the target value of the first observation, multiplied by 1000
model.predict(features)[0]*1000

24573.366631705547

In [6]:
# first coeffeicient * 1000
model.coef_[0]*1000

-352.07831564026765

## 13.2 Handling Interactive Effects
* Polynomial Features

In [8]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.preprocessing import PolynomialFeatures

boston = load_boston()
features = boston.data[:, 0:2]
target = boston.target
interaction = PolynomialFeatures(
    degree=3, include_bias=False, interaction_only=True
)

features_interaction = interaction.fit_transform(features)

# linear regression
regression = LinearRegression()

# Fit the model
model = regression.fit(features_interaction, target)

In [9]:
features[0]

array([6.32e-03, 1.80e+01])

In [10]:
import numpy as np

# each obs, multiply the values of the first and second feature
interaction_term = np.multiply(features[:, 0], features[:, 1])

In [12]:
interaction_term[0]

0.11376

In [13]:
# view the values of the first obs
features_interaction[0]

array([6.3200e-03, 1.8000e+01, 1.1376e-01])

## 13.3 Fitting a Nonlinear Relationship

* Polynomial regression

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.preprocessing import PolynomialFeatures

boston = load_boston()
features = boston.data[:, 0:1]
target = boston.target

# polynomial features x^2, x^3
polynomial = PolynomialFeatures(degree=3, include_bias=False)
features_polynomical = polynomial.fit_transform(features)

# linear regression
regression = LinearRegression()

# FIt
model = regression.fit(features,target)


In [18]:
features[0]

array([0.00632])

In [19]:
# View first obs raised to the 2nd power, x^2
features[0]**2

array([3.99424e-05])

In [21]:
# first obs's values for x, x^2, x^3
features_polynomical[0]

array([6.32000000e-03, 3.99424000e-05, 2.52435968e-07])

## 13.4 Reducing Variance with Regularization

In [23]:
from sklearn.linear_model import Ridge
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler

boston = load_boston()
features = boston.data
target = boston.target

# Standardize features
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

# Create ridge regression with an alpha value
regression = Ridge(alpha=0.5)

# Fit the linear regression
model = regression.fit(features_standardized, target)

In [24]:
from sklearn.linear_model import RidgeCV

regr_cv = RidgeCV(alphas=[0.1, 1.0, 10.0])

model_cv = regr_cv.fit(features_standardized, target)

# view coeff
model_cv.coef_

array([-0.91987132,  1.06646104,  0.11738487,  0.68512693, -2.02901013,
        2.68275376,  0.01315848, -3.07733968,  2.59153764, -2.0105579 ,
       -2.05238455,  0.84884839, -3.73066646])

In [25]:
# view the alpha
model_cv.alpha_

1.0

## 13.5 Reducing Features with LASSO regression
* simplify your linear regression model by reducing the number of features

In [26]:
from sklearn.linear_model import Lasso
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler

boston = load_boston()
features = boston.data
target = boston.target

scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

regression = Lasso(alpha=0.5)

model = regression.fit(features_standardized, target)

* LASSO : 많은 변수를 줄일 수 있다.
* 특히 그 coefficients가 0이 되는 것을 확인할 수 있다.

In [27]:
model.coef_

array([-0.11526463,  0.        , -0.        ,  0.39707879, -0.        ,
        2.97425861, -0.        , -0.17056942, -0.        , -0.        ,
       -1.59844856,  0.54313871, -3.66614361])

In [28]:
regression_a10 = Lasso(alpha=10)
model_a10 = regression_a10.fit(features_standardized, target)
model_a10.coef_

array([-0.,  0., -0.,  0., -0.,  0., -0.,  0., -0., -0., -0.,  0., -0.])

* alpha가 10으로 매우 커지게 되면서, 우리는 모든 변수가 0이된 것을 확인할 수 있다.
* 이 경우에 100개의 피처 행렬에서 오직 10개의 중요한 피처만을 사용한 모델을 만들어 낼 수 있다. 이는 우리 모델의 해석 가능성을 상당히 높여줄 것으로 기대된다.